service: react-express-lambda-ts

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'

provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

package:
  exclude:
    - "**/*.ts"
    - "test/**"
    - "client/**"
    - "scripts/**"
    - ".vscode/**"
    - "*"
  include:
    - "client/build/**"

functions:
  http:
    handler: server/lambda.http
    timeout: 2
    events:
      - http: ANY /
      - http: ANY /{proxy+}
